# Generated by Django 4.0.5 on 2022-06-09 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=80, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.auto', verbose_name='Автмобіль')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
