# Generated by Django 4.0.5 on 2022-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_image'),
        ('customauth', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(related_name='Частини', to='cars.part'),
        ),
    ]
