# Generated by Django 4.0.5 on 2022-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_auto_parts_alter_auto_image_completeset_and_more'),
        ('customauth', '0003_order_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
        migrations.AddField(
            model_name='order',
            name='complete_set',
            field=models.ManyToManyField(related_name='Комплектація', to='cars.completeset'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
