# Generated by Django 4.0.5 on 2022-06-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_auto_parts_alter_auto_image_completeset_and_more'),
        ('customauth', '0004_remove_order_parts_order_complete_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='В обробці'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='order',
            name='complete_set',
        ),
        migrations.AddField(
            model_name='order',
            name='complete_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.completeset', verbose_name='Комплектація'),
        ),
    ]
