# Generated by Django 4.0.5 on 2022-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0007_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Оброблено'),
        ),
    ]
