# Generated by Django 4.0.5 on 2022-06-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_auto_parts_alter_auto_image_completeset_and_more'),
        ('customauth', '0008_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.auto', verbose_name='Автмобіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.completeset', verbose_name='Комплектація'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
