# Generated by Django 4.0.5 on 2022-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('type', models.CharField(choices=[('EN', 'Двигун'), ('GB', 'Коробка передач'), ('DR', 'Привід'), ('FT', "Об'єм паливного бака"), ('OT', 'Інше')], max_length=2, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Частина',
                'verbose_name_plural': 'Частини',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('parts', models.ManyToManyField(to='cars.part', verbose_name='Частини')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
    ]
