# Generated by Django 4.0.5 on 2022-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='parts',
        ),
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фотографія'),
        ),
        migrations.CreateModel(
            name='CompleteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.ManyToManyField(to='cars.part', verbose_name='Комплектація')),
            ],
            options={
                'verbose_name': 'Комплектація',
                'verbose_name_plural': 'Комплектації',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='complete_sets',
            field=models.ManyToManyField(to='cars.completeset', verbose_name='Комплектації'),
        ),
    ]
